const NOW = 1721272800000; // Fixed timestamp to prevent SSR hydration errors

export const MOCK_AGENTS = [
  {
    id: 'agent-001',
    name: 'Alex Morgan',
    email: 'alex.morgan@rapiddispatch.com',
    avatar: null,
    department: 'Operations',
    role: 'senior_agent',
    status: 'online',
    active_tickets: 4,
  },
  {
    id: 'agent-002',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@rapiddispatch.com',
    avatar: null,
    department: 'Support',
    role: 'agent',
    status: 'online',
    active_tickets: 6,
  },
  {
    id: 'agent-003',
    name: 'Emma Wilson',
    email: 'emma.wilson@rapiddispatch.com',
    avatar: null,
    department: 'Support',
    role: 'agent',
    status: 'online',
    active_tickets: 3,
  },
  {
    id: 'agent-004',
    name: 'Michael Chen',
    email: 'michael.chen@rapiddispatch.com',
    avatar: null,
    department: 'Dispatch',
    role: 'dispatcher',
    status: 'idle',
    active_tickets: 5,
  },
  {
    id: 'agent-005',
    name: 'John Davis',
    email: 'john.davis@rapiddispatch.com',
    avatar: null,
    department: 'Operations',
    role: 'team_lead',
    status: 'away',
    active_tickets: 2,
  },
];

export const MOCK_TICKETS = [
  {
    id: 't-001',
    ticket_number: 10042,
    customer_name: 'Robert Hernandez',
    company: 'Pacific Freight Lines',
    truck_number: 'TRK-4821',
    issue: 'Engine failure on I-40 near Amarillo, TX. Truck carrying refrigerated goods — cargo at risk of spoilage. Needs immediate roadside assistance and cargo transfer.',
    priority: 'critical',
    status: 'in_progress',
    assigned_agent: 'Sarah Johnson',
    locked_by: 'Sarah Johnson',
    locked_at: new Date(NOW - 180000).toISOString(),
    created_at: new Date(NOW - 3600000).toISOString(),
    updated_at: new Date(NOW - 180000).toISOString(),
    last_activity: 'Sarah added a note: "Roadside unit dispatched ETA 25 min"',
    location: 'Amarillo, TX',
    sla_remaining: 1800000,
    unread_count: 3,
    issue_type: 'breakdown',
  },
  {
    id: 't-002',
    ticket_number: 10041,
    customer_name: 'Lisa Chang',
    company: 'Summit Logistics Corp',
    truck_number: 'TRK-7733',
    issue: 'Shipment delayed at Memphis hub for 18 hours. Customer demanding status update. Original delivery window was 6 AM today.',
    priority: 'high',
    status: 'assigned',
    assigned_agent: 'Alex Morgan',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 7200000).toISOString(),
    updated_at: new Date(NOW - 900000).toISOString(),
    last_activity: 'Customer called asking for update',
    location: 'Memphis, TN',
    sla_remaining: 3600000,
    unread_count: 1,
    issue_type: 'delay',
  },
  {
    id: 't-003',
    ticket_number: 10040,
    customer_name: 'James O\'Brien',
    company: 'Midwest Express Haulers',
    truck_number: 'TRK-1156',
    issue: 'Driver reports flat tire on trailer axle 3. Currently parked at rest area on I-70 westbound mile marker 212. Load is non-perishable.',
    priority: 'medium',
    status: 'open',
    assigned_agent: null,
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 5400000).toISOString(),
    updated_at: new Date(NOW - 5400000).toISOString(),
    last_activity: 'Ticket created via driver app',
    location: 'Kansas City, MO',
    sla_remaining: 7200000,
    unread_count: 0,
    issue_type: 'breakdown',
  },
  {
    id: 't-004',
    ticket_number: 10039,
    customer_name: 'Maria Santos',
    company: 'CrossBorder Transport Inc',
    truck_number: 'TRK-9044',
    issue: 'Customs hold at Laredo border crossing. Missing Certificate of Origin for electronics shipment. Broker unresponsive.',
    priority: 'high',
    status: 'waiting_customer',
    assigned_agent: 'Michael Chen',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 14400000).toISOString(),
    updated_at: new Date(NOW - 3600000).toISOString(),
    last_activity: 'Awaiting Certificate of Origin from shipper',
    location: 'Laredo, TX',
    sla_remaining: 5400000,
    unread_count: 2,
    issue_type: 'customs',
  },
  {
    id: 't-005',
    ticket_number: 10038,
    customer_name: 'Kevin Park',
    company: 'Golden State Carriers',
    truck_number: 'TRK-2290',
    issue: 'Incorrect delivery address on BOL. Driver arrived at warehouse but location is permanently closed. Need updated delivery instructions.',
    priority: 'medium',
    status: 'in_progress',
    assigned_agent: 'Emma Wilson',
    locked_by: 'Emma Wilson',
    locked_at: new Date(NOW - 600000).toISOString(),
    created_at: new Date(NOW - 10800000).toISOString(),
    updated_at: new Date(NOW - 600000).toISOString(),
    last_activity: 'Emma is contacting the consignee for new address',
    location: 'Fresno, CA',
    sla_remaining: 4500000,
    unread_count: 0,
    issue_type: 'delivery_issue',
  },
  {
    id: 't-006',
    ticket_number: 10037,
    customer_name: 'Angela Foster',
    company: 'Northeast Freight Solutions',
    truck_number: 'TRK-5517',
    issue: 'Reefer unit temperature alarm. Current temp 48°F, required 34°F. Pharmaceutical cargo at risk. Driver has pulled over.',
    priority: 'critical',
    status: 'new',
    assigned_agent: null,
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 300000).toISOString(),
    updated_at: new Date(NOW - 300000).toISOString(),
    last_activity: 'Auto-created from IoT temperature alert',
    location: 'Hartford, CT',
    sla_remaining: 900000,
    unread_count: 1,
    issue_type: 'temperature_alert',
  },
  {
    id: 't-007',
    ticket_number: 10036,
    customer_name: 'David Kim',
    company: 'Cascade Trucking LLC',
    truck_number: 'TRK-3381',
    issue: 'Driver involved in minor fender bender at distribution center parking lot. No injuries. Need incident report filed and insurance contacted.',
    priority: 'medium',
    status: 'assigned',
    assigned_agent: 'John Davis',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 21600000).toISOString(),
    updated_at: new Date(NOW - 7200000).toISOString(),
    last_activity: 'Photos uploaded by driver',
    location: 'Portland, OR',
    sla_remaining: 14400000,
    unread_count: 4,
    issue_type: 'accident',
  },
  {
    id: 't-008',
    ticket_number: 10035,
    customer_name: 'Susan Martinez',
    company: 'Lone Star Logistics',
    truck_number: 'TRK-6698',
    issue: 'Overweight at weigh station on I-10. Load needs to be redistributed or partial offload arranged. 2,400 lbs over limit.',
    priority: 'high',
    status: 'in_progress',
    assigned_agent: 'Alex Morgan',
    locked_by: 'Alex Morgan',
    locked_at: new Date(NOW - 900000).toISOString(),
    created_at: new Date(NOW - 7200000).toISOString(),
    updated_at: new Date(NOW - 900000).toISOString(),
    last_activity: 'Coordinating with nearby warehouse for partial offload',
    location: 'San Antonio, TX',
    sla_remaining: 2700000,
    unread_count: 2,
    issue_type: 'compliance',
  },
  {
    id: 't-009',
    ticket_number: 10034,
    customer_name: 'Thomas Wright',
    company: 'Great Lakes Shipping Co',
    truck_number: 'TRK-8102',
    issue: 'Customer refusing delivery — claims damaged packaging on 12 pallets. Driver waiting at dock. Need authorization for return or partial delivery.',
    priority: 'high',
    status: 'assigned',
    assigned_agent: 'Sarah Johnson',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 9000000).toISOString(),
    updated_at: new Date(NOW - 1800000).toISOString(),
    last_activity: 'Sarah escalated to claims department',
    location: 'Detroit, MI',
    sla_remaining: 1200000,
    unread_count: 5,
    issue_type: 'damage_claim',
  },
  {
    id: 't-010',
    ticket_number: 10033,
    customer_name: 'Patricia Nguyen',
    company: 'Harbor Point Distributors',
    truck_number: 'TRK-4455',
    issue: 'Driver hours of service violation approaching. 30-minute break required within next 45 minutes but no safe parking available on current route.',
    priority: 'medium',
    status: 'resolved',
    assigned_agent: 'Michael Chen',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 28800000).toISOString(),
    updated_at: new Date(NOW - 14400000).toISOString(),
    last_activity: 'Rest stop identified at mile marker 88. Driver confirmed.',
    location: 'Nashville, TN',
    sla_remaining: 0,
    unread_count: 0,
    issue_type: 'compliance',
  },
  {
    id: 't-011',
    ticket_number: 10032,
    customer_name: 'Richard Bell',
    company: 'Keystone Freight Corp',
    truck_number: 'TRK-2017',
    issue: 'GPS tracker offline for truck carrying high-value electronics. Last known position was I-95 near Philadelphia 4 hours ago.',
    priority: 'critical',
    status: 'in_progress',
    assigned_agent: 'Alex Morgan',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 14400000).toISOString(),
    updated_at: new Date(NOW - 3600000).toISOString(),
    last_activity: 'Alex contacted driver via satellite phone — truck is at rest area, GPS unit malfunctioned',
    location: 'Philadelphia, PA',
    sla_remaining: 600000,
    unread_count: 1,
    issue_type: 'tracking',
  },
  {
    id: 't-012',
    ticket_number: 10031,
    customer_name: 'Jennifer Adams',
    company: 'Sun Valley Transport',
    truck_number: 'TRK-7890',
    issue: 'Scheduled pickup at warehouse but dock not available until 4 PM. Driver has been waiting since 8 AM. Requesting detention pay authorization.',
    priority: 'low',
    status: 'waiting_customer',
    assigned_agent: 'Emma Wilson',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 43200000).toISOString(),
    updated_at: new Date(NOW - 21600000).toISOString(),
    last_activity: 'Awaiting shipper approval for detention charges',
    location: 'Phoenix, AZ',
    sla_remaining: 28800000,
    unread_count: 0,
    issue_type: 'detention',
  },
  {
    id: 't-013',
    ticket_number: 10030,
    customer_name: 'William Torres',
    company: 'Atlantic Cargo Systems',
    truck_number: 'TRK-1234',
    issue: 'Hazmat placard missing from trailer. Driver noticed during pre-trip inspection. Cannot legally proceed without proper placarding.',
    priority: 'high',
    status: 'open',
    assigned_agent: null,
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 1800000).toISOString(),
    updated_at: new Date(NOW - 1800000).toISOString(),
    last_activity: 'Ticket created — needs dispatch coordination',
    location: 'Charlotte, NC',
    sla_remaining: 3600000,
    unread_count: 1,
    issue_type: 'compliance',
  },
  {
    id: 't-014',
    ticket_number: 10029,
    customer_name: 'Nancy Cooper',
    company: 'Redwood Shipping Inc',
    truck_number: 'TRK-5566',
    issue: 'Delivery completed but POD signature unclear. Customer disputing receipt of 3 pallets. Need driver statement and unloading photos.',
    priority: 'low',
    status: 'closed',
    assigned_agent: 'John Davis',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 86400000).toISOString(),
    updated_at: new Date(NOW - 43200000).toISOString(),
    last_activity: 'Resolved — driver photos confirm all 3 pallets delivered',
    location: 'Sacramento, CA',
    sla_remaining: 0,
    unread_count: 0,
    issue_type: 'documentation',
  },
  {
    id: 't-015',
    ticket_number: 10028,
    customer_name: 'Charles Lee',
    company: 'Iron Range Transport',
    truck_number: 'TRK-9921',
    issue: 'Route closure on I-35 due to winter storm. Need alternate route planning for 53-foot trailer. Current route adds 6 hours.',
    priority: 'medium',
    status: 'reopened',
    assigned_agent: 'Michael Chen',
    locked_by: null,
    locked_at: null,
    created_at: new Date(NOW - 36000000).toISOString(),
    updated_at: new Date(NOW - 7200000).toISOString(),
    last_activity: 'Alternate route also reporting closures — reopened for new planning',
    location: 'Minneapolis, MN',
    sla_remaining: 5400000,
    unread_count: 3,
    issue_type: 'route_issue',
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: 'act-001',
    event_type: 'ticket_locked',
    agent_name: 'Sarah Johnson',
    ticket_number: 10042,
    description: 'Sarah locked Ticket #10042 — engine failure case',
    created_at: new Date(NOW - 60000).toISOString(),
  },
  {
    id: 'act-002',
    event_type: 'priority_changed',
    agent_name: 'Alex Morgan',
    ticket_number: 10041,
    description: 'Alex escalated Ticket #10041 from Medium to High',
    created_at: new Date(NOW - 180000).toISOString(),
  },
  {
    id: 'act-003',
    event_type: 'ticket_created',
    agent_name: 'System',
    ticket_number: 10037,
    description: 'Ticket #10037 auto-created from IoT temperature alert',
    created_at: new Date(NOW - 300000).toISOString(),
  },
  {
    id: 'act-004',
    event_type: 'comment_added',
    agent_name: 'Emma Wilson',
    ticket_number: 10038,
    description: 'Emma added: "Contacting consignee for new delivery address"',
    created_at: new Date(NOW - 450000).toISOString(),
  },
  {
    id: 'act-005',
    event_type: 'ticket_assigned',
    agent_name: 'John Davis',
    ticket_number: 10036,
    description: 'Ticket #10036 assigned to John Davis',
    created_at: new Date(NOW - 720000).toISOString(),
  },
  {
    id: 'act-006',
    event_type: 'status_changed',
    agent_name: 'Michael Chen',
    ticket_number: 10033,
    description: 'Michael resolved Ticket #10033 — HOS violation averted',
    created_at: new Date(NOW - 900000).toISOString(),
  },
  {
    id: 'act-007',
    event_type: 'attachment_uploaded',
    agent_name: 'Sarah Johnson',
    ticket_number: 10034,
    description: 'Sarah uploaded damage_photos.zip to Ticket #10034',
    created_at: new Date(NOW - 1200000).toISOString(),
  },
  {
    id: 'act-008',
    event_type: 'customer_replied',
    agent_name: 'Customer',
    ticket_number: 10039,
    description: 'Customer replied on Ticket #10039 — Certificate of Origin attached',
    created_at: new Date(NOW - 1500000).toISOString(),
  },
];

export const MOCK_MESSAGES = [
  { id: 'm-001', ticket_id: 't-001', author: 'Robert Hernandez', role: 'customer', message: 'Our perishable goods are time-sensitive. We need an updated ETA immediately and compensation for potential spoilage.', created_at: new Date(NOW - 3.5 * 3600000).toISOString() },
  { id: 'm-002', ticket_id: 't-001', author: 'Sarah Johnson', role: 'agent', message: 'I understand the urgency, Robert. I\'ve dispatched roadside assistance. ETA is 25 mins. I\'m escalating the compensation request to our claims department.', created_at: new Date(NOW - 3 * 3600000).toISOString() },
];

export const MOCK_KPI_DATA = {
  activeTickets: 10,
  lockedTickets: 2,
  criticalTickets: 4,
  waitingCustomer: 2,
  onlineAgents: 4,
  avgResponseTime: '12m',
  avgResolutionTime: '2.4h',
  slaViolations: 1,
  customerSatisfaction: 94,
  reopenedTickets: 0,
  resolvedToday: 3,
  pendingTickets: 5,
};
